/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dizan
 */
public class vistaEvaporadores extends javax.swing.JFrame {
    /**
     * Creates new form vistaEvaporadores
     */
    
    public DefaultTableModel modeloTabla;
    
    public vistaEvaporadores() {
        initComponents();
        scrollResultados.getViewport().setBackground(new Color(8,38,67));
        modeloTabla = (DefaultTableModel) tablaResultados.getModel() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoPresion_O_Temperatura = new javax.swing.ButtonGroup();
        grupoTemp_O_PresionUltimoEfecto = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelVariablesConocidas = new javax.swing.JPanel();
        labelNumeroEfectos = new javax.swing.JLabel();
        labelArreglo = new javax.swing.JLabel();
        labelFlujoAlimentacion = new javax.swing.JLabel();
        labelConcentracionAlimentacion = new javax.swing.JLabel();
        labelPresionVaporAlimentacion = new javax.swing.JLabel();
        labelTemperaturaVaporAlimentacion = new javax.swing.JLabel();
        labelConcentracionFinalConcentrada = new javax.swing.JLabel();
        labelTemperaturaUltimoEfecto = new javax.swing.JLabel();
        labelPresionUltimoEfecto = new javax.swing.JLabel();
        labelCoeficientesGlobales = new javax.swing.JLabel();
        labelCapacidadCalorifica = new javax.swing.JLabel();
        labelTemperaturaAlimentacion = new javax.swing.JLabel();
        fieldNumeroEfectos = new javax.swing.JTextField();
        fieldArreglo = new javax.swing.JTextField();
        fieldFlujoAlimentacion = new javax.swing.JTextField();
        fieldConcentracionAlimentacion = new javax.swing.JTextField();
        fieldPresionVaporAlimentacion = new javax.swing.JTextField();
        fieldTemperaturaVaporAlimentacion = new javax.swing.JTextField();
        fieldConcentracionFinalConcentrada = new javax.swing.JTextField();
        fieldTemperaturaUltimoEfecto = new javax.swing.JTextField();
        fieldPresionUltimoEfecto = new javax.swing.JTextField();
        fieldCoeficientesGlobales = new javax.swing.JTextField();
        fieldCapacidadCalorifica = new javax.swing.JTextField();
        fieldTemperaturaAlimentacion = new javax.swing.JTextField();
        checkPresionAlimentacion = new javax.swing.JCheckBox();
        checkTemperaturaAlimentacion = new javax.swing.JCheckBox();
        checkkTemperaturaUltimoEfecto = new javax.swing.JCheckBox();
        checkPresionUltimoEfecto = new javax.swing.JCheckBox();
        botonIngresarValoresCoeficientesGlobales = new javax.swing.JButton();
        botonIngresarValoresArreglo = new javax.swing.JButton();
        botonVerValoresCoeficientesGlobales = new javax.swing.JButton();
        botonVerValoresArreglo = new javax.swing.JButton();
        boxUnidadFlujoAlientacion = new javax.swing.JComboBox<>();
        boxUnidadPresionAlimentacion = new javax.swing.JComboBox<>();
        boxUnidadTempVaporAlimentacion = new javax.swing.JComboBox<>();
        boxUnidadTemperaturaUltimoEfecto = new javax.swing.JComboBox<>();
        boxUnidadPresionUltimoEfecto = new javax.swing.JComboBox<>();
        boxUnidadCoeficientesGlobales = new javax.swing.JComboBox<>();
        boxUnidadCapacidadCalorifica = new javax.swing.JComboBox<>();
        boxUnidadTemperaturaAlimentacion = new javax.swing.JComboBox<>();
        panelVacio2 = new javax.swing.JPanel();
        panelDatosCadaEvaporador = new javax.swing.JPanel();
        scrollResultados = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        panelDatosSistema = new javax.swing.JPanel();
        labelEconomiaSistema = new javax.swing.JLabel();
        labelCapacidadSistema = new javax.swing.JLabel();
        labelV0 = new javax.swing.JLabel();
        fieldEconomiaSistema = new javax.swing.JTextField();
        fieldCapacidadSistema = new javax.swing.JTextField();
        fieldV0 = new javax.swing.JTextField();
        panelVacio = new javax.swing.JPanel();
        botonCalcular = new javax.swing.JButton();
        botonNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALGORITMO PARA EL DISEÑO DE EVAPORADORES DE MÚLTIPLE EFECTO");
        setExtendedState(MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(950, 650));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelPrincipal.setBackground(new java.awt.Color(8, 38, 67));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        PanelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        PanelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelTitulo.setLayout(new java.awt.GridBagLayout());

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("ALGORITMO PARA EL DISEÑO DE EVAPORADORES DE MÚLTIPLE EFECTO");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        PanelTitulo.add(labelTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        panelPrincipal.add(PanelTitulo, gridBagConstraints);

        panelVariablesConocidas.setBackground(new java.awt.Color(8, 38, 67));
        panelVariablesConocidas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelVariablesConocidas.setLayout(new java.awt.GridBagLayout());

        labelNumeroEfectos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumeroEfectos.setForeground(new java.awt.Color(255, 255, 255));
        labelNumeroEfectos.setText("Numero de efectos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelVariablesConocidas.add(labelNumeroEfectos, gridBagConstraints);

        labelArreglo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelArreglo.setForeground(new java.awt.Color(255, 255, 255));
        labelArreglo.setText("Arreglo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelArreglo, gridBagConstraints);

        labelFlujoAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFlujoAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        labelFlujoAlimentacion.setText("Flujo de alimentacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelFlujoAlimentacion, gridBagConstraints);

        labelConcentracionAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelConcentracionAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        labelConcentracionAlimentacion.setText("Concentracion de la alimentacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelConcentracionAlimentacion, gridBagConstraints);

        labelPresionVaporAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPresionVaporAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        labelPresionVaporAlimentacion.setText("Presión del vapor de alimentación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelPresionVaporAlimentacion, gridBagConstraints);

        labelTemperaturaVaporAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTemperaturaVaporAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        labelTemperaturaVaporAlimentacion.setText("Temperatura del vapor de alimentación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelTemperaturaVaporAlimentacion, gridBagConstraints);

        labelConcentracionFinalConcentrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelConcentracionFinalConcentrada.setForeground(new java.awt.Color(255, 255, 255));
        labelConcentracionFinalConcentrada.setText("Concentración final de la solución concentrada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelConcentracionFinalConcentrada, gridBagConstraints);

        labelTemperaturaUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTemperaturaUltimoEfecto.setForeground(new java.awt.Color(255, 255, 255));
        labelTemperaturaUltimoEfecto.setText("Temperatura del vapor proveniente del último efecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelTemperaturaUltimoEfecto, gridBagConstraints);

        labelPresionUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPresionUltimoEfecto.setForeground(new java.awt.Color(255, 255, 255));
        labelPresionUltimoEfecto.setText("Presión del vapor proveniente del último efecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelPresionUltimoEfecto, gridBagConstraints);

        labelCoeficientesGlobales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCoeficientesGlobales.setForeground(new java.awt.Color(255, 255, 255));
        labelCoeficientesGlobales.setText("Coeficientes globales de transferencia de calor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(labelCoeficientesGlobales, gridBagConstraints);

        labelCapacidadCalorifica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCapacidadCalorifica.setForeground(new java.awt.Color(255, 255, 255));
        labelCapacidadCalorifica.setText("Capacidad calorífica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        panelVariablesConocidas.add(labelCapacidadCalorifica, gridBagConstraints);

        labelTemperaturaAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTemperaturaAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        labelTemperaturaAlimentacion.setText("Temperatura de la alimentación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        panelVariablesConocidas.add(labelTemperaturaAlimentacion, gridBagConstraints);

        fieldNumeroEfectos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldNumeroEfectos.setForeground(new java.awt.Color(153, 153, 153));
        fieldNumeroEfectos.setText("N");
        fieldNumeroEfectos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNumeroEfectosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNumeroEfectosFocusLost(evt);
            }
        });
        fieldNumeroEfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroEfectosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 50);
        panelVariablesConocidas.add(fieldNumeroEfectos, gridBagConstraints);

        fieldArreglo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldArreglo.setForeground(new java.awt.Color(153, 153, 153));
        fieldArreglo.setText("Cantidad evap.");
        fieldArreglo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldArregloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldArregloFocusLost(evt);
            }
        });
        fieldArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldArregloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldArreglo, gridBagConstraints);

        fieldFlujoAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldFlujoAlimentacion.setForeground(new java.awt.Color(153, 153, 153));
        fieldFlujoAlimentacion.setText("F");
        fieldFlujoAlimentacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFlujoAlimentacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldFlujoAlimentacionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldFlujoAlimentacion, gridBagConstraints);

        fieldConcentracionAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldConcentracionAlimentacion.setForeground(new java.awt.Color(153, 153, 153));
        fieldConcentracionAlimentacion.setText("XF");
        fieldConcentracionAlimentacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldConcentracionAlimentacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldConcentracionAlimentacionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldConcentracionAlimentacion, gridBagConstraints);

        fieldPresionVaporAlimentacion.setEditable(false);
        fieldPresionVaporAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldPresionVaporAlimentacion.setForeground(new java.awt.Color(153, 153, 153));
        fieldPresionVaporAlimentacion.setText("P0");
        fieldPresionVaporAlimentacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPresionVaporAlimentacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPresionVaporAlimentacionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldPresionVaporAlimentacion, gridBagConstraints);

        fieldTemperaturaVaporAlimentacion.setEditable(false);
        fieldTemperaturaVaporAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldTemperaturaVaporAlimentacion.setForeground(new java.awt.Color(153, 153, 153));
        fieldTemperaturaVaporAlimentacion.setText("T0");
        fieldTemperaturaVaporAlimentacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldTemperaturaVaporAlimentacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldTemperaturaVaporAlimentacionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldTemperaturaVaporAlimentacion, gridBagConstraints);

        fieldConcentracionFinalConcentrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldConcentracionFinalConcentrada.setForeground(new java.awt.Color(153, 153, 153));
        fieldConcentracionFinalConcentrada.setText("XAN");
        fieldConcentracionFinalConcentrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldConcentracionFinalConcentradaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldConcentracionFinalConcentradaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldConcentracionFinalConcentrada, gridBagConstraints);

        fieldTemperaturaUltimoEfecto.setEditable(false);
        fieldTemperaturaUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldTemperaturaUltimoEfecto.setForeground(new java.awt.Color(153, 153, 153));
        fieldTemperaturaUltimoEfecto.setText("TN");
        fieldTemperaturaUltimoEfecto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldTemperaturaUltimoEfectoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldTemperaturaUltimoEfectoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldTemperaturaUltimoEfecto, gridBagConstraints);

        fieldPresionUltimoEfecto.setEditable(false);
        fieldPresionUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldPresionUltimoEfecto.setForeground(new java.awt.Color(153, 153, 153));
        fieldPresionUltimoEfecto.setText("PN");
        fieldPresionUltimoEfecto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPresionUltimoEfectoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPresionUltimoEfectoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldPresionUltimoEfecto, gridBagConstraints);

        fieldCoeficientesGlobales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldCoeficientesGlobales.setForeground(new java.awt.Color(153, 153, 153));
        fieldCoeficientesGlobales.setText("Escribir la cantidad");
        fieldCoeficientesGlobales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCoeficientesGlobalesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCoeficientesGlobalesFocusLost(evt);
            }
        });
        fieldCoeficientesGlobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCoeficientesGlobalesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldCoeficientesGlobales, gridBagConstraints);

        fieldCapacidadCalorifica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldCapacidadCalorifica.setForeground(new java.awt.Color(153, 153, 153));
        fieldCapacidadCalorifica.setText("Cp");
        fieldCapacidadCalorifica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCapacidadCalorificaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCapacidadCalorificaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldCapacidadCalorifica, gridBagConstraints);

        fieldTemperaturaAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldTemperaturaAlimentacion.setForeground(new java.awt.Color(153, 153, 153));
        fieldTemperaturaAlimentacion.setText("TF");
        fieldTemperaturaAlimentacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldTemperaturaAlimentacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldTemperaturaAlimentacionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 50);
        panelVariablesConocidas.add(fieldTemperaturaAlimentacion, gridBagConstraints);

        checkPresionAlimentacion.setBackground(new java.awt.Color(8, 38, 67));
        grupoPresion_O_Temperatura.add(checkPresionAlimentacion);
        checkPresionAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPresionAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        checkPresionAlimentacion.setText("Seleccionar");
        checkPresionAlimentacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkPresionAlimentacionItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(checkPresionAlimentacion, gridBagConstraints);

        checkTemperaturaAlimentacion.setBackground(new java.awt.Color(8, 38, 67));
        grupoPresion_O_Temperatura.add(checkTemperaturaAlimentacion);
        checkTemperaturaAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkTemperaturaAlimentacion.setForeground(new java.awt.Color(255, 255, 255));
        checkTemperaturaAlimentacion.setText("Selecciona");
        checkTemperaturaAlimentacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkTemperaturaAlimentacionItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(checkTemperaturaAlimentacion, gridBagConstraints);

        checkkTemperaturaUltimoEfecto.setBackground(new java.awt.Color(8, 38, 67));
        grupoTemp_O_PresionUltimoEfecto.add(checkkTemperaturaUltimoEfecto);
        checkkTemperaturaUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkkTemperaturaUltimoEfecto.setForeground(new java.awt.Color(255, 255, 255));
        checkkTemperaturaUltimoEfecto.setText("Seleccionar");
        checkkTemperaturaUltimoEfecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkkTemperaturaUltimoEfectoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(checkkTemperaturaUltimoEfecto, gridBagConstraints);

        checkPresionUltimoEfecto.setBackground(new java.awt.Color(8, 38, 67));
        grupoTemp_O_PresionUltimoEfecto.add(checkPresionUltimoEfecto);
        checkPresionUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkPresionUltimoEfecto.setForeground(new java.awt.Color(255, 255, 255));
        checkPresionUltimoEfecto.setText("Seleccionar");
        checkPresionUltimoEfecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkPresionUltimoEfectoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVariablesConocidas.add(checkPresionUltimoEfecto, gridBagConstraints);

        botonIngresarValoresCoeficientesGlobales.setBackground(new java.awt.Color(153, 0, 51));
        botonIngresarValoresCoeficientesGlobales.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresarValoresCoeficientesGlobales.setText("Ingresar Valores");
        botonIngresarValoresCoeficientesGlobales.setFocusPainted(false);
        botonIngresarValoresCoeficientesGlobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarValoresCoeficientesGlobalesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(botonIngresarValoresCoeficientesGlobales, gridBagConstraints);

        botonIngresarValoresArreglo.setBackground(new java.awt.Color(153, 0, 51));
        botonIngresarValoresArreglo.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresarValoresArreglo.setText("Ingresar arreglo");
        botonIngresarValoresArreglo.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(botonIngresarValoresArreglo, gridBagConstraints);

        botonVerValoresCoeficientesGlobales.setBackground(new java.awt.Color(153, 0, 51));
        botonVerValoresCoeficientesGlobales.setForeground(new java.awt.Color(255, 255, 255));
        botonVerValoresCoeficientesGlobales.setText("Ver valores");
        botonVerValoresCoeficientesGlobales.setEnabled(false);
        botonVerValoresCoeficientesGlobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerValoresCoeficientesGlobalesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(botonVerValoresCoeficientesGlobales, gridBagConstraints);

        botonVerValoresArreglo.setBackground(new java.awt.Color(153, 0, 51));
        botonVerValoresArreglo.setForeground(new java.awt.Color(255, 255, 255));
        botonVerValoresArreglo.setText("Ver valores");
        botonVerValoresArreglo.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(botonVerValoresArreglo, gridBagConstraints);

        boxUnidadFlujoAlientacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadFlujoAlientacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg/h", "lb/h" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadFlujoAlientacion, gridBagConstraints);

        boxUnidadPresionAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadPresionAlimentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kpa", "atm", "lb/in²", "lb/ftp²", "mmHg" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadPresionAlimentacion, gridBagConstraints);

        boxUnidadTempVaporAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadTempVaporAlimentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadTempVaporAlimentacion, gridBagConstraints);

        boxUnidadTemperaturaUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadTemperaturaUltimoEfecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadTemperaturaUltimoEfecto, gridBagConstraints);

        boxUnidadPresionUltimoEfecto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadPresionUltimoEfecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kpa", "atm", "lb/in²", "lb/ftp²", "mmHg" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadPresionUltimoEfecto, gridBagConstraints);

        boxUnidadCoeficientesGlobales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadCoeficientesGlobales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KJ/m²h°C", "KCal/m²h°C", "Btu/ft²h°F", "W/m²°C" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadCoeficientesGlobales, gridBagConstraints);

        boxUnidadCapacidadCalorifica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadCapacidadCalorifica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KJ/Kg°C", "Cal/g°C", "Btu/lb°F" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadCapacidadCalorifica, gridBagConstraints);

        boxUnidadTemperaturaAlimentacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxUnidadTemperaturaAlimentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelVariablesConocidas.add(boxUnidadTemperaturaAlimentacion, gridBagConstraints);

        panelVacio2.setBackground(new java.awt.Color(8, 38, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.weightx = 1.0;
        panelVariablesConocidas.add(panelVacio2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        panelPrincipal.add(panelVariablesConocidas, gridBagConstraints);

        panelDatosCadaEvaporador.setBackground(new java.awt.Color(8, 38, 67));
        panelDatosCadaEvaporador.setLayout(new java.awt.GridLayout(1, 0));

        scrollResultados.setBackground(new java.awt.Color(0, 102, 102));

        tablaResultados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Evaporador", "Entalpia (KJ/Kg)", "Flujo de vapor (Kg/h)", "Presion (KPa)", "Flujo de liquido (Kg/h)", "Concentracion liq. Con.", "Superficie de calefacción (m²)", "Temp. Finales (°C)"
            }
        ));
        scrollResultados.setViewportView(tablaResultados);
        if (tablaResultados.getColumnModel().getColumnCount() > 0) {
            tablaResultados.getColumnModel().getColumn(0).setMinWidth(70);
            tablaResultados.getColumnModel().getColumn(0).setPreferredWidth(70);
            tablaResultados.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        panelDatosCadaEvaporador.add(scrollResultados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        panelPrincipal.add(panelDatosCadaEvaporador, gridBagConstraints);

        panelDatosSistema.setBackground(new java.awt.Color(8, 38, 67));
        panelDatosSistema.setLayout(new java.awt.GridBagLayout());

        labelEconomiaSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEconomiaSistema.setForeground(new java.awt.Color(255, 255, 255));
        labelEconomiaSistema.setText("Economía del sistema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 20);
        panelDatosSistema.add(labelEconomiaSistema, gridBagConstraints);

        labelCapacidadSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCapacidadSistema.setForeground(new java.awt.Color(255, 255, 255));
        labelCapacidadSistema.setText("Capacidad del sistema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelDatosSistema.add(labelCapacidadSistema, gridBagConstraints);

        labelV0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelV0.setForeground(new java.awt.Color(255, 255, 255));
        labelV0.setText("V0:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelDatosSistema.add(labelV0, gridBagConstraints);

        fieldEconomiaSistema.setEditable(false);
        fieldEconomiaSistema.setBackground(new java.awt.Color(0, 87, 126));
        fieldEconomiaSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldEconomiaSistema.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelDatosSistema.add(fieldEconomiaSistema, gridBagConstraints);

        fieldCapacidadSistema.setEditable(false);
        fieldCapacidadSistema.setBackground(new java.awt.Color(0, 87, 126));
        fieldCapacidadSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldCapacidadSistema.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelDatosSistema.add(fieldCapacidadSistema, gridBagConstraints);

        fieldV0.setEditable(false);
        fieldV0.setBackground(new java.awt.Color(0, 87, 126));
        fieldV0.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldV0.setForeground(new java.awt.Color(255, 255, 255));
        fieldV0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        panelDatosSistema.add(fieldV0, gridBagConstraints);

        panelVacio.setBackground(new java.awt.Color(8, 38, 67));
        panelVacio.setLayout(new java.awt.GridBagLayout());

        botonCalcular.setBackground(new java.awt.Color(0, 87, 126));
        botonCalcular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCalcular.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcular.setText("Calcular");
        botonCalcular.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        panelVacio.add(botonCalcular, gridBagConstraints);

        botonNuevo.setBackground(new java.awt.Color(0, 102, 102));
        botonNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonNuevo.setForeground(new java.awt.Color(255, 255, 255));
        botonNuevo.setText("Nuevo Cálculo");
        botonNuevo.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        panelVacio.add(botonNuevo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelDatosSistema.add(panelVacio, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        panelPrincipal.add(panelDatosSistema, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNumeroEfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroEfectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroEfectosActionPerformed

    private void fieldArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldArregloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldArregloActionPerformed

    private void fieldNumeroEfectosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroEfectosFocusGained
        if ("N".equals(fieldNumeroEfectos.getText())) {
            fieldNumeroEfectos.setText("");
            fieldNumeroEfectos.setForeground(Color.BLACK);  
        }
    }//GEN-LAST:event_fieldNumeroEfectosFocusGained

    private void fieldNumeroEfectosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroEfectosFocusLost
        if (fieldNumeroEfectos.getText().isEmpty()) {
            fieldNumeroEfectos.setText("N");
            fieldNumeroEfectos.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldNumeroEfectosFocusLost

    private void fieldArregloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldArregloFocusGained
        if ("Cantidad evap.".equals(fieldArreglo.getText())) {
            fieldArreglo.setText("");
            fieldArreglo.setForeground(Color.BLACK); 
        }
        botonIngresarValoresArreglo.setEnabled(true);
    }//GEN-LAST:event_fieldArregloFocusGained

    private void fieldArregloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldArregloFocusLost
         if(fieldArreglo.getText().isEmpty()) {
            fieldArreglo.setText("Cantidad evap.");
            fieldArreglo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldArregloFocusLost

    private void fieldFlujoAlimentacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFlujoAlimentacionFocusGained
            if ("F".equals(fieldFlujoAlimentacion.getText())) {
            fieldFlujoAlimentacion.setText("");
            fieldFlujoAlimentacion.setForeground(Color.BLACK);
        }        
    }//GEN-LAST:event_fieldFlujoAlimentacionFocusGained

    private void fieldFlujoAlimentacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFlujoAlimentacionFocusLost
        if(fieldFlujoAlimentacion.getText().isEmpty()) {
            fieldFlujoAlimentacion.setText("F");
            fieldFlujoAlimentacion.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldFlujoAlimentacionFocusLost

    private void fieldConcentracionAlimentacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldConcentracionAlimentacionFocusGained
        if ("XF".equals(fieldConcentracionAlimentacion.getText())) {
            fieldConcentracionAlimentacion.setText("");
            fieldConcentracionAlimentacion.setForeground(Color.BLACK);  
        }    
    }//GEN-LAST:event_fieldConcentracionAlimentacionFocusGained

    private void fieldConcentracionAlimentacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldConcentracionAlimentacionFocusLost
        if( fieldConcentracionAlimentacion.getText().isEmpty()) {
            fieldConcentracionAlimentacion.setText("XF");
            fieldConcentracionAlimentacion.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldConcentracionAlimentacionFocusLost

    private void fieldPresionVaporAlimentacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPresionVaporAlimentacionFocusGained
        if ("P0".equals(fieldPresionVaporAlimentacion.getText())) {
            fieldPresionVaporAlimentacion.setText("");
            fieldPresionVaporAlimentacion.setForeground(Color.BLACK);  
        }    
    }//GEN-LAST:event_fieldPresionVaporAlimentacionFocusGained

    private void fieldPresionVaporAlimentacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPresionVaporAlimentacionFocusLost
        if( fieldPresionVaporAlimentacion.getText().isEmpty()) {
            fieldPresionVaporAlimentacion.setText("P0");
            fieldPresionVaporAlimentacion.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldPresionVaporAlimentacionFocusLost

    private void fieldTemperaturaVaporAlimentacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldTemperaturaVaporAlimentacionFocusGained
        if ("T0".equals(fieldTemperaturaVaporAlimentacion.getText())) {
            fieldTemperaturaVaporAlimentacion.setText("");
            fieldTemperaturaVaporAlimentacion.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_fieldTemperaturaVaporAlimentacionFocusGained

    private void fieldTemperaturaVaporAlimentacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldTemperaturaVaporAlimentacionFocusLost
        if( fieldTemperaturaVaporAlimentacion.getText().isEmpty()) {
            fieldTemperaturaVaporAlimentacion.setText("T0");
            fieldTemperaturaVaporAlimentacion.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldTemperaturaVaporAlimentacionFocusLost

    private void fieldConcentracionFinalConcentradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldConcentracionFinalConcentradaFocusGained
        if ("XAN".equals(fieldConcentracionFinalConcentrada.getText())) {
            fieldConcentracionFinalConcentrada.setText("");
            fieldConcentracionFinalConcentrada.setForeground(Color.BLACK); 
        }    
    }//GEN-LAST:event_fieldConcentracionFinalConcentradaFocusGained

    private void fieldConcentracionFinalConcentradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldConcentracionFinalConcentradaFocusLost
        if( fieldConcentracionFinalConcentrada.getText().isEmpty()) {
            fieldConcentracionFinalConcentrada.setText("XAN");
            fieldConcentracionFinalConcentrada.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldConcentracionFinalConcentradaFocusLost

    private void fieldTemperaturaUltimoEfectoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldTemperaturaUltimoEfectoFocusGained
        if ("TN".equals(fieldTemperaturaUltimoEfecto.getText())) {
            fieldTemperaturaUltimoEfecto.setText("");
            fieldTemperaturaUltimoEfecto.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_fieldTemperaturaUltimoEfectoFocusGained

    private void fieldTemperaturaUltimoEfectoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldTemperaturaUltimoEfectoFocusLost
         if(fieldTemperaturaUltimoEfecto.getText().isEmpty()) {
            fieldTemperaturaUltimoEfecto.setText("TN");
            fieldTemperaturaUltimoEfecto.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldTemperaturaUltimoEfectoFocusLost

    private void fieldCoeficientesGlobalesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCoeficientesGlobalesFocusGained
        if ("Escribir la cantidad".equals(fieldCoeficientesGlobales.getText())) {
            fieldCoeficientesGlobales.setText("");
            fieldCoeficientesGlobales.setForeground(Color.BLACK); 
        }   
        botonIngresarValoresCoeficientesGlobales.setEnabled(true);
    }//GEN-LAST:event_fieldCoeficientesGlobalesFocusGained

    private void fieldCoeficientesGlobalesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCoeficientesGlobalesFocusLost
        if(fieldCoeficientesGlobales.getText().isEmpty()) {
           fieldCoeficientesGlobales.setText("Escribir la cantidad");
           fieldCoeficientesGlobales.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldCoeficientesGlobalesFocusLost

    private void fieldCapacidadCalorificaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCapacidadCalorificaFocusGained
        if ("Cp".equals(fieldCapacidadCalorifica.getText())) {
            fieldCapacidadCalorifica.setText("");
            fieldCapacidadCalorifica.setForeground(Color.BLACK); 
        }   
    }//GEN-LAST:event_fieldCapacidadCalorificaFocusGained

    private void fieldCapacidadCalorificaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCapacidadCalorificaFocusLost
        if(fieldCapacidadCalorifica.getText().isEmpty()) {
           fieldCapacidadCalorifica.setText("Cp");
           fieldCapacidadCalorifica.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldCapacidadCalorificaFocusLost

    private void checkPresionAlimentacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkPresionAlimentacionItemStateChanged
        int seleccionado = evt.getStateChange();
  
        if (seleccionado == ItemEvent.SELECTED) {
           fieldPresionVaporAlimentacion.setEditable(true);
        }
        if (seleccionado == ItemEvent.DESELECTED) {
           fieldPresionVaporAlimentacion.setEditable(false);
           fieldPresionVaporAlimentacion.setText("P0");
           fieldPresionVaporAlimentacion.setForeground(new Color(153, 153, 153));
        } 
    }//GEN-LAST:event_checkPresionAlimentacionItemStateChanged

    private void checkTemperaturaAlimentacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkTemperaturaAlimentacionItemStateChanged
        int seleccionado = evt.getStateChange();
        
        if (seleccionado == ItemEvent.SELECTED) {
           fieldTemperaturaVaporAlimentacion.setEditable(true);
        }
        if (seleccionado == ItemEvent.DESELECTED) {
           fieldTemperaturaVaporAlimentacion.setEditable(false);
           fieldTemperaturaVaporAlimentacion.setText("T0");
           fieldTemperaturaVaporAlimentacion.setForeground(new Color(153, 153, 153)); 
        } 
    }//GEN-LAST:event_checkTemperaturaAlimentacionItemStateChanged

    private void fieldCoeficientesGlobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCoeficientesGlobalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCoeficientesGlobalesActionPerformed

    private void botonVerValoresCoeficientesGlobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerValoresCoeficientesGlobalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerValoresCoeficientesGlobalesActionPerformed

    private void botonIngresarValoresCoeficientesGlobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarValoresCoeficientesGlobalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresarValoresCoeficientesGlobalesActionPerformed

    private void fieldTemperaturaAlimentacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldTemperaturaAlimentacionFocusGained
        if ("TF".equals(fieldTemperaturaAlimentacion.getText())) {
            fieldTemperaturaAlimentacion.setText("");
            fieldTemperaturaAlimentacion.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_fieldTemperaturaAlimentacionFocusGained

    private void fieldTemperaturaAlimentacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldTemperaturaAlimentacionFocusLost

        if(fieldTemperaturaAlimentacion.getText().isEmpty()) {
           fieldTemperaturaAlimentacion.setText("TF");
           fieldTemperaturaAlimentacion.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldTemperaturaAlimentacionFocusLost

    private void fieldPresionUltimoEfectoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPresionUltimoEfectoFocusGained
        if ("PN".equals(fieldPresionUltimoEfecto.getText())) {
            fieldPresionUltimoEfecto.setText("");
            fieldPresionUltimoEfecto.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_fieldPresionUltimoEfectoFocusGained

    private void fieldPresionUltimoEfectoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPresionUltimoEfectoFocusLost
         if(fieldPresionUltimoEfecto.getText().isEmpty()) {
           fieldPresionUltimoEfecto.setText("PN");
           fieldPresionUltimoEfecto.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldPresionUltimoEfectoFocusLost

    private void checkPresionUltimoEfectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkPresionUltimoEfectoItemStateChanged
        int seleccionado = evt.getStateChange();
        
        if (seleccionado == ItemEvent.SELECTED) {
           fieldPresionUltimoEfecto.setEditable(true);
        }
        if (seleccionado == ItemEvent.DESELECTED) {
           fieldPresionUltimoEfecto.setEditable(false);
           fieldPresionUltimoEfecto.setText("PN");
           fieldPresionUltimoEfecto.setForeground(new Color(153, 153, 153)); 
        } 
    }//GEN-LAST:event_checkPresionUltimoEfectoItemStateChanged

    private void checkkTemperaturaUltimoEfectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkkTemperaturaUltimoEfectoItemStateChanged
        int seleccionado = evt.getStateChange();
        
        if (seleccionado == ItemEvent.SELECTED) {
           fieldTemperaturaUltimoEfecto.setEditable(true);
        }
        if (seleccionado == ItemEvent.DESELECTED) {
           fieldTemperaturaUltimoEfecto.setEditable(false);
           fieldTemperaturaUltimoEfecto.setText("TN");
           fieldTemperaturaUltimoEfecto.setForeground(new Color(153, 153, 153)); 
        } 
    }//GEN-LAST:event_checkkTemperaturaUltimoEfectoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEvaporadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEvaporadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEvaporadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEvaporadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaEvaporadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTitulo;
    public javax.swing.JButton botonCalcular;
    public javax.swing.JButton botonIngresarValoresArreglo;
    public javax.swing.JButton botonIngresarValoresCoeficientesGlobales;
    public javax.swing.JButton botonNuevo;
    public javax.swing.JButton botonVerValoresArreglo;
    public javax.swing.JButton botonVerValoresCoeficientesGlobales;
    public javax.swing.JComboBox<String> boxUnidadCapacidadCalorifica;
    public javax.swing.JComboBox<String> boxUnidadCoeficientesGlobales;
    public javax.swing.JComboBox<String> boxUnidadFlujoAlientacion;
    public javax.swing.JComboBox<String> boxUnidadPresionAlimentacion;
    public javax.swing.JComboBox<String> boxUnidadPresionUltimoEfecto;
    public javax.swing.JComboBox<String> boxUnidadTempVaporAlimentacion;
    public javax.swing.JComboBox<String> boxUnidadTemperaturaAlimentacion;
    public javax.swing.JComboBox<String> boxUnidadTemperaturaUltimoEfecto;
    public javax.swing.JCheckBox checkPresionAlimentacion;
    public javax.swing.JCheckBox checkPresionUltimoEfecto;
    public javax.swing.JCheckBox checkTemperaturaAlimentacion;
    public javax.swing.JCheckBox checkkTemperaturaUltimoEfecto;
    public javax.swing.JTextField fieldArreglo;
    public javax.swing.JTextField fieldCapacidadCalorifica;
    public javax.swing.JTextField fieldCapacidadSistema;
    public javax.swing.JTextField fieldCoeficientesGlobales;
    public javax.swing.JTextField fieldConcentracionAlimentacion;
    public javax.swing.JTextField fieldConcentracionFinalConcentrada;
    public javax.swing.JTextField fieldEconomiaSistema;
    public javax.swing.JTextField fieldFlujoAlimentacion;
    public javax.swing.JTextField fieldNumeroEfectos;
    public javax.swing.JTextField fieldPresionUltimoEfecto;
    public javax.swing.JTextField fieldPresionVaporAlimentacion;
    public javax.swing.JTextField fieldTemperaturaAlimentacion;
    public javax.swing.JTextField fieldTemperaturaUltimoEfecto;
    public javax.swing.JTextField fieldTemperaturaVaporAlimentacion;
    public javax.swing.JTextField fieldV0;
    private javax.swing.ButtonGroup grupoPresion_O_Temperatura;
    private javax.swing.ButtonGroup grupoTemp_O_PresionUltimoEfecto;
    private javax.swing.JLabel labelArreglo;
    private javax.swing.JLabel labelCapacidadCalorifica;
    private javax.swing.JLabel labelCapacidadSistema;
    private javax.swing.JLabel labelCoeficientesGlobales;
    private javax.swing.JLabel labelConcentracionAlimentacion;
    private javax.swing.JLabel labelConcentracionFinalConcentrada;
    private javax.swing.JLabel labelEconomiaSistema;
    private javax.swing.JLabel labelFlujoAlimentacion;
    private javax.swing.JLabel labelNumeroEfectos;
    private javax.swing.JLabel labelPresionUltimoEfecto;
    private javax.swing.JLabel labelPresionVaporAlimentacion;
    private javax.swing.JLabel labelTemperaturaAlimentacion;
    private javax.swing.JLabel labelTemperaturaUltimoEfecto;
    private javax.swing.JLabel labelTemperaturaVaporAlimentacion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelV0;
    private javax.swing.JPanel panelDatosCadaEvaporador;
    private javax.swing.JPanel panelDatosSistema;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JPanel panelVacio2;
    private javax.swing.JPanel panelVariablesConocidas;
    private javax.swing.JScrollPane scrollResultados;
    public javax.swing.JTable tablaResultados;
    // End of variables declaration//GEN-END:variables
}
